CREATE SEQUENCE IF NOT EXISTS customer_sequence start
WITH
  1 increment by 1;

CREATE SEQUENCE IF NOT EXISTS address_sequence start
WITH
  1 increment by 1;

CREATE TABLE address (
  created TIMESTAMP(6) WITH TIME ZONE,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  updated TIMESTAMP(6) WITH TIME ZONE,
  version BIGINT,
  city VARCHAR(255),
  country VARCHAR(255),
  postal_code VARCHAR(255),
  province VARCHAR(255),
  street VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE customer (
  address_id BIGINT,
  created TIMESTAMP(6) WITH TIME ZONE,
  department_id BIGINT,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  updated TIMESTAMP(6) WITH TIME ZONE,
  version BIGINT,
  email VARCHAR(255),
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  phone_number VARCHAR(255),
  birth_date DATE,
  birth_place VARCHAR(255),
  privacy BOOLEAN,
  children_description VARCHAR(255),
  education_level VARCHAR(255),
  gender VARCHAR(255),
  marital_status VARCHAR(255),
  preferred_region VARCHAR(255),
  profession VARCHAR(255),
  sector VARCHAR(255),
  PRIMARY KEY (id),
  CONSTRAINT customer_email_index UNIQUE (email),
  FOREIGN KEY (address_id) REFERENCES address(id)
);
