CREATE SEQUENCE IF NOT EXISTS employee_sequence start
WITH
  1 increment by 1;

CREATE SEQUENCE IF NOT EXISTS address_sequence start
WITH
  1 increment by 1;

CREATE SEQUENCE IF NOT EXISTS project_sequence start
WITH
  1 increment by 1;

CREATE SEQUENCE IF NOT EXISTS department_sequence start
WITH
  1 increment by 1;

CREATE TABLE address (
  created TIMESTAMP(6) WITH TIME ZONE,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  updated TIMESTAMP(6) WITH TIME ZONE,
  version BIGINT,
  city VARCHAR(255),
  country VARCHAR(255),
  postal_code VARCHAR(255),
  state VARCHAR(255),
  street VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE department (
  created TIMESTAMP(6) WITH TIME ZONE,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  updated TIMESTAMP(6) WITH TIME ZONE,
  version BIGINT,
  code VARCHAR(255),
  name VARCHAR(255),
  PRIMARY KEY (id),
  CONSTRAINT department_code_index UNIQUE (code)
);

CREATE TABLE employee (
  address_id BIGINT,
  created TIMESTAMP(6) WITH TIME ZONE,
  department_id BIGINT,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  updated TIMESTAMP(6) WITH TIME ZONE,
  version BIGINT,
  email VARCHAR(255),
  name VARCHAR(255),
  phone_number VARCHAR(255),
  PRIMARY KEY (id),
  CONSTRAINT employee_email_index UNIQUE (email),
  FOREIGN KEY (address_id) REFERENCES address(id),
  FOREIGN KEY (department_id) REFERENCES department(id)
);

CREATE TABLE project (
  created TIMESTAMP(6) WITH TIME ZONE,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  updated TIMESTAMP(6) WITH TIME ZONE,
  version BIGINT,
  code VARCHAR(255),
  name VARCHAR(255),
  PRIMARY KEY (id),
  CONSTRAINT project_code_index UNIQUE (code)
);

CREATE TABLE employee_projects (
  employees_id BIGINT NOT NULL,
  projects_id BIGINT NOT NULL,
  FOREIGN KEY (projects_id) REFERENCES project(id),
  FOREIGN KEY (employees_id) REFERENCES employee(id)
);
