name: CI action with Gradle

on:
  push:
    branches:
      - "main"

jobs:
  build:
    uses:
      mandraghen/gh-actions-template/.github/workflows/build-gradle.yaml@main
    secrets: inherit
  dockerize:
    needs: build
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses:
      mandraghen/gh-actions-template/.github/workflows/dockerize.yaml@main

  local-k8s-deploy:
    needs: dockerize
    uses: mandraghen/gh-actions-template/.github/workflows/promote.yaml@main
    with:
      environment: local-k8s
      app-name: user-service
    secrets: inherit
